development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ball_hockey_app
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: heroku_51451079c0f297e
  pool: 5
  username: b48fbdab919965
  password: b9648ef6
  host: us-cdbr-iron-east-05.cleardb.net